### ISSUE TITLE
script fails when certain dependencies are already installed

### ISSUE THREAD

**Issue by maryamklabib** [cloudfoundry/capi-workspace#4]
Script exited when installing google chrome because I had already installed it. 

![screen shot 2018-02-28 at 1 39 35 pm](https://user-images.githubusercontent.com/4147717/36814597-e1ab03be-1c8c-11e8-9861-10ad2515ff84.png)

**Comment by infews** [comment]
This error happens when an application was installed some other way than brew. This happens when you get a machine that has some applications installed before we run`./install.sh`. I'm not sure this is preventable, but I do wish that Homebrew had a better error message than this.

Closing for now.
