### ISSUE TITLE
Installing consul fails on a clean install because it requires authentication

### ISSUE THREAD

**Issue by maryamklabib** [cloudfoundry/capi-workspace#5]
![screen shot 2018-02-28 at 1 45 24 pm](https://user-images.githubusercontent.com/4147717/36814880-bf2144f6-1c8d-11e8-9e91-bedcf76757d9.png)

This didn't work even when I put my github key in

**Comment by infews** [comment]
Should we consider removing consul from this script? We only need consul in order to run the bridge tests. The most recent run had consul not build at all. Closing for now.

**Comment by selzoc** [comment]
Removed consul installation in https://github.com/cloudfoundry/capi-workspace/commit/51596aa9f5ac228cefd227c05cf7660a14ebe6a4
